name: Pull Request CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop
jobs:
  build-features:
    if: startsWith(github.head_ref, 'feature/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Setup Java JDK
        uses: actions/setup-java@v5.4.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Download Maven dependencies
        run: mvn -B -DskipTests dependency:go-offline

      - name: Compile project
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Build project
        run: mvn package -DskipTests
